---
# tasks file for Setting-phpmyadmin-by-ansible-role
- include: install.yml
  tags:
    - install

- include: nginx-setup.yml
  tags:
    - nginx

- include: phpmyadmin-setup.yml
  tags:
    - phpmyadmin
