- name: Nginx Settup
  template:
    src: site.j2
    dest: /etc/nginx/sites-available/{{ debian_name }}
  tags:
    - nginx_settup

- name: Enabling {{ debian_name }}
  file:
    src: /etc/nginx/sites-available/{{ debian_name }}
    dest: /etc/nginx/sites-enabled/{{ debian_name }}
    state: link
  tags:
    - nginx_settup

- name: "{{ debian_name  }} settup"
  file:
    state: directory
    dest:  /var/www/{{ debian_name }}
    mode:  0755

- name: Default index.html fie for {{ debian_name }}
  template:
    src: index.html.j2
    dest: /var/www/{{ debian_name }}/index.html
