- name: Nginx Setup
  template:
    src: site.j2
    dest: /etc/nginx/sites-available/{{ debian_name }}
  tags:
    - nginx_setup
  notify: "Restart nginx"

- name: Disabling default
  file:
    name: /etc/nginx/sites-enabled/default
    state: absent
  when: nginx_port == 80 and disable_default | bool
  notify: "Restart nginx"

- name: Enabling {{ debian_name }}
  file:
    src: /etc/nginx/sites-available/{{ debian_name }}
    dest: /etc/nginx/sites-enabled/{{ debian_name }}
    state: link
  tags:
    - nginx_setup
  notify: "Restart nginx" 

- name: "{{ debian_name  }} setup"
  file:
    state: directory
    dest:  "{{ root }}/{{ debian_name }}"
    mode:  0755
  tags:
    - nginx_setup

- name: Default index.html file for {{ debian_name }}
  template:
    src: index.html.j2
    dest: "{{ root }}/{{ debian_name }}/index.html"
  tags:
    - nginx_setup
